### ISSUE TITLE
classy_spacy.py raises "NotImplementedError: internal spacy embeddings need to be derived from md/lg spacy models not from sm/trf models."

### ISSUE THREAD

**Issue by kbillesk** [Pandora-Intelligence/classy-classification#22]
Thanks for a very nice module! A problem has been introduced with the new version.
The error is raised when adding the pipe:
My code looks like this:
```python
nlp = spacy.load("en_core_web_lg")
nlp.add_pipe("text_categorizer", config={"data": training_data,"model": "spacy"})
```
The console output in Spyder is:
```bash
File "c:\users\krist\documents\python scripts\doc genres\examples\classifiertest_dk.py", line 21, in <module>
    nlp.add_pipe("text_categorizer", config={"data": training_data,"model": "spacy", "include_sent": False})

  File "C:\Users\krist\anaconda3\envs\spyder-env\lib\site-packages\spacy\language.py", line 801, in add_pipe
    pipe_component = self.create_pipe(

  File "C:\Users\krist\anaconda3\envs\spyder-env\lib\site-packages\spacy\language.py", line 680, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)

  File "C:\Users\krist\anaconda3\envs\spyder-env\lib\site-packages\confection\__init__.py", line 728, in resolve
    resolved, _ = cls._make(

  File "C:\Users\krist\anaconda3\envs\spyder-env\lib\site-packages\confection\__init__.py", line 777, in _make
    filled, _, resolved = cls._fill(

  File "C:\Users\krist\anaconda3\envs\spyder-env\lib\site-packages\confection\__init__.py", line 849, in _fill
    getter_result = getter(*args, **kwargs)

  File "C:\Users\krist\anaconda3\envs\spyder-env\lib\site-packages\classy_classification\__init__.py", line 65, in make_text_categorizer
    return classySpacyInternalFewShot(

  File "C:\Users\krist\anaconda3\envs\spyder-env\lib\site-packages\classy_classification\classifiers\classy_spacy.py", line 104, in __init__
    classySkeletonFewShot.__init__(self, *args, **kwargs)

  File "C:\Users\krist\anaconda3\envs\spyder-env\lib\site-packages\classy_classification\classifiers\classy_skeleton.py", line 63, in __init__
    self.set_training_data()

  File "C:\Users\krist\anaconda3\envs\spyder-env\lib\site-packages\classy_classification\classifiers\classy_skeleton.py", line 187, in set_training_data
    self.X = self.get_embeddings(X)

  File "C:\Users\krist\anaconda3\envs\spyder-env\lib\site-packages\classy_classification\classifiers\classy_spacy.py", line 95, in get_embeddings
    raise NotImplementedError(

NotImplementedError: internal spacy embeddings need to be derived from md/lg spacy models not from sm/trf models.
```
Thanks in advance

**Comment by davidberenstein1957** [comment]
@kbillesk thanks for the issue, I will take a look the week after Christmas.

**Comment by davidberenstein1957** [comment]
@kbillesk I cannot reproduce this. Could you share your complete code?

**Comment by davidberenstein1957** [comment]
@kbillesk I added `trf`support in the new 0.5.4 release. Happy Holidays 🎄

**Comment by kbillesk** [comment]
Just tested it. Thanks a lot and have lovely New Year!

**Comment by brownyaroundtown** [comment]
@davidberenstein1957 I ran into a very similar type of issue with v6.0 running on Python 3.8 where "print([sent._.cats for sent in nlp(validation_data[0]).sents])" works fine, but "print([doc._.cats for doc in nlp.pipe(validation_data)])" spits out an error even though I am loading a spacy model with vectors ("en_core_web_lg")

`nlp = spacy.load("en_core_web_lg")
nlp.add_pipe(
    "text_categorizer",
    config={
        "data": data,
        "model": "spacy",
        "include_sent": True,
        "multi_label": True,

print([doc._.cats for doc in nlp.pipe(validation_data)])
`

`
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[93], line 2
      1 print([sent._.cats for sent in nlp(validation_data[0]).sents])
----> 2 print([doc._.cats for doc in nlp.pipe(validation_data)])

Cell In[93], line 2, in <listcomp>(.0)
      1 print([sent._.cats for sent in nlp(validation_data[0]).sents])
----> 2 print([doc._.cats for doc in nlp.pipe(validation_data)])

File /opt/conda/envs/python38_classy_class/lib/python3.8/site-packages/spacy/language.py:1589, in Language.pipe(self, texts, as_tuples, batch_size, disable, component_cfg, n_process)
   1587     for pipe in pipes:
   1588         docs = pipe(docs)
-> 1589 for doc in docs:
   1590     yield doc

File /opt/conda/envs/python38_classy_class/lib/python3.8/site-packages/spacy/util.py:1651, in _pipe(docs, proc, name, default_error_handler, kwargs)
   1643 def _pipe(
   1644     docs: Iterable["Doc"],
   1645     proc: "Pipe",
   (...)
   1648     kwargs: Mapping[str, Any],
   1649 ) -> Iterator["Doc"]:
   1650     if hasattr(proc, "pipe"):
-> 1651         yield from proc.pipe(docs, **kwargs)
   1652     else:
   1653         # We added some args for pipe that __call__ doesn't expect.
   1654         kwargs = dict(kwargs)

File /opt/conda/envs/python38_classy_class/lib/python3.8/site-packages/classy_classification/classifiers/classy_spacy.py:56, in ClassySpacy.pipe(self, stream, batch_size, include_sent)
     54     include_sent = self.include_sent
     55 for docs in util.minibatch(stream, size=batch_size):
---> 56     embeddings = self.get_embeddings(docs)
     57     pred_results = [] * len(embeddings)
     58     if self.include_doc:

File /opt/conda/envs/python38_classy_class/lib/python3.8/site-packages/classy_classification/classifiers/classy_spacy.py:98, in ClassySpacyInternal.get_embeddings(self, docs)
     96             embeddings.append(doc._.trf_data.model_output.pooler_output[0])
     97         else:
---> 98             raise NotImplementedError(
     99                 "internal spacy embeddings need to be derived from md/lg/trf spacy models not from sm models."
    100             )
    102 return np.array(embeddings)

NotImplementedError: internal spacy embeddings need to be derived from md/lg/trf spacy models not from sm models.
`

**Comment by davidberenstein1957** [comment]
Hi, @brownyaroundtown what versions are you using?

**Comment by brownyaroundtown** [comment]
> 

it's the latest version v6.0 - I think I figured it out though, some of my input validation data values were 'bad' - like "location3" is an example.  I believe because it's not an actual word that would be on the language model's vector I get the error.  If I remove the "3" and just have 'location' in the list of validation data it seems to work fine.

**Comment by davidberenstein1957** [comment]
I resoled this in the latest version, thanks for the feedback @brownyaroundtown
